### ISSUE TITLE
revert_to_snapshot(vm_name, snapshot_name) function should be implemented

### ISSUE THREAD

**Issue by GeorgeFischhof** [jossef/vmwc#2]
Hi There

revert_to_snapshot(vm_name, snapshot_name) function should be implemented

something like this:

```
def revert_to_snapshot(self, vm_name, snapshot_name):

    virtual_machine = self.get_virtual_machine(self.vm_name)
    snapshots = virtual_machine.get_snapshots()
    for snapshot in snapshots:
        if snapshot.name == self.snapshot_name:
            snapshot.revert()
```

BR,
George

**Comment by jossef** [comment]
hey buddy, it's already implemented

https://github.com/jossef/vmwc/blob/master/vmwc/__init__.py#L651

Thanks!

**Comment by jossef** [comment]
Looks Great. @GeorgeFischhof Could you make a PR about this suggestion?

**Comment by GeorgeFischhof** [comment]
Thank you. PR: on my workplace I will tell this to my colleagues ;-)
