### ISSUE TITLE
Missing function: vm.shutdown()

### ISSUE THREAD

**Issue by GeorgeFischhof** [jossef/vmwc#6]
Hi there,

I started to use vmwc (again ;-) ) (it is so good now ;-) ), but I could not find vm.shutdown function. As I know power_off only shuts down the vm when this behaviour is set using vm-tools.
So it would be good to have a shutdown function.

BR,
George

**Comment by jossef** [comment]
great suggestion, 
could you please fork, add missing implementation and return with pull request?

**Comment by GeorgeFischhof** [comment]
HI,

I use different objects, so I think it would not be good in your package.

I send my stuff here insted. ;-) (right now it is a command line version)

I hope it will help you.

BR,
George


import atexit
import ssl
import time

import click
from pyVim import connect
from pyVmomi import vim


@click.group()
def main():
pass


def _get_esx_content(host, username, password):
# monkey patch to disable cert verification as we use sef-signed cert
ssl._create_default_https_context = ssl._create_unverified_context

service_instance = connect.Connect(host=host, user=username, pwd=password)
atexit.register(connect.Disconnect, service_instance)
content = service_instance.content

return content


def _get_virtual_machines(content):
object_types_to_view = [vim.VirtualMachine]
recursive = True
container_view = content.viewManager.CreateContainerView(
content.rootFolder, object_types_to_view, recursive)

virtual_machines = container_view.view
return virtual_machines


def _get_virtual_machine(vmname, content):
virtual_machines = _get_virtual_machines(content)
for virtual_machine in virtual_machines:
if virtual_machine.summary.config.name == vmname:
return virtual_machine


@main.command()
@click.option('/host', '--host', help='IP address or hostname of the ESX
host', prompt=True)
@click.option('/username', '--username', help='Username for ESX', prompt=
True)
@click.option('/password', '--password', help='Password for ESX user',
prompt=True, hide_input=True)
@click.option('/vmname', '--vmname', help='Name of the virtual machine',
prompt=True)
def vm_power_shutdown(vmname, host, username, password):
content = _get_esx_content(host, username, password)
vm = _get_virtual_machine(vmname, content)
vm.ShutdownGuest()
# while vm.GuestInfo.GuestState == 'shuttingDown':
# time.sleep(1)
time.sleep(20)


@main.command()
@click.option('/host', '--host', help='IP address or hostname of the ESX
host', prompt=True)
@click.option('/username', '--username', help='Username for ESX', prompt=
True)
@click.option('/password', '--password', help='Password for ESX user',
prompt=True, hide_input=True)
@click.option('/vmname', '--vmname', help='Name of the virtual machine',
prompt=True)
def get_vm_ip(vmname, host, username, password):
content = _get_esx_content(host, username, password)
vm = _get_virtual_machine(vmname, content)
ip_address = vm.summary.guest.ipAddress
print(ip_address)
return ip_address


if __name__ == '__main__':
main()




















2018-03-28 12:50 GMT+02:00 Jossef Harush <notifications@github.com>:

**Comment by jossef** [comment]
feature added to [v1.0.3](https://github.com/jossef/vmwc/releases/tag/1.0.3)
