### ISSUE TITLE
At remote command execution the working dir can not be empty

### ISSUE THREAD

**Issue by GeorgeFischhof** [jossef/vmwc#7]
https://github.com/jossef/vmwc/blob/495ed130ecd614f0e87191a6ea5636a232c1d1eb/vmwc/__init__.py#L693

Hi there,

in the line above the working dir has a default value of None.
It seems to be bad, neither the None nor the empty string did work for me, it worked only when I added the path of the command to the working directory.

used:
remote guest: windows 2016 server
vmware: esx 6.0
pyvmomi 6.5.0.2017.5-1
python 3.6.3

BR,
George

**Comment by jossef** [comment]
thanks for the report
when provided with `None` I'm thinking about using the dirname of the program_path as a fallback
will that work for you?

**Comment by GeorgeFischhof** [comment]
Hi Jossef,

now I am working at a different workplace, unfortunately I am not able try
this.

BR,
George

2018-03-28 12:53 GMT+02:00 Jossef Harush <notifications@github.com>:

**Comment by jossef** [comment]
making `working_directory` a mandatory parameter. Why?

### VMware recommends explicitly setting the working directory for the program to be run

>workingDirectory (str, optional):
>The absolute path of the working directory for the program to be run. **VMware recommends explicitly setting the working directory for the program to be run**. If this value is unset or is an empty string, the behavior depends on the guest operating system. For Linux guest operating systems, if this value is unset or is an empty string, the working directory will be the home directory of the user associated with the guest authentication. For other guest operating systems, if this value is unset, the behavior is unspecified.
